[package]
name = "opencv_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
clang-sys = "1.8.1"
opencv = "0.92.0"
libc = "0.2"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=-crt-static"]